export const birlaOpusCategories = [
  "Interior Paints",
  "Exterior Paints",
  "Waterproofing",
  "Enamels",
  "Wood Finishes",
  "Wallpapers",
  "Tools",
  "Aerosols"
] as const;

export type BirlaOpusCategory = (typeof birlaOpusCategories)[number];

export const birlaOpusProductCount = 124;

export const birlaOpusProducts = [
  {
    "name": "Alpha Ever Wash",
    "family": "Alpha",
    "slug": "alpha-ever-wash",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Alpha_Ever_Wash.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/alpha-ever-wash"
  },
  {
    "name": "Calista Ever Clear",
    "family": "Calista",
    "slug": "calista-ever-clear",
    "category": "Interior Paints",
    "copy": "High-performance washable interior emulsion delivering smooth radiance and scrub-resistant durability.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Ever_Clear.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/calista-ever-clear"
  },
  {
    "name": "Calista Ever Clear Matt",
    "family": "Calista",
    "slug": "calista-ever-clear-matt",
    "category": "Interior Paints",
    "copy": "High-performance washable interior emulsion delivering smooth radiance and scrub-resistant durability.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Ever_Clear_Matt.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/calista-ever-clear-matt"
  },
  {
    "name": "Calista Ever Stay",
    "family": "Calista",
    "slug": "calista-ever-stay",
    "category": "Interior Paints",
    "copy": "High-performance washable interior emulsion delivering smooth radiance and scrub-resistant durability.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Ever_Stay.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/calista-ever-stay"
  },
  {
    "name": "Calista Ever Wash",
    "family": "Calista",
    "slug": "calista-ever-wash",
    "category": "Interior Paints",
    "copy": "High-performance washable interior emulsion delivering smooth radiance and scrub-resistant durability.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Ever_Wash.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/calista-ever-wash"
  },
  {
    "name": "Calista Ever Wash Shine",
    "family": "Calista",
    "slug": "calista-ever-wash-shine",
    "category": "Interior Paints",
    "copy": "High-performance washable interior emulsion delivering smooth radiance and scrub-resistant durability.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Ever_Wash_Shine.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/calista-ever-wash-shine"
  },
  {
    "name": "Calista Pro White Primer",
    "family": "Calista",
    "slug": "calista-pro-white-primer",
    "category": "Interior Paints",
    "copy": "Deep-penetrating substrate primer ensuring superior adhesion and uniform sheen across interior plaster.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Calista_Pro_White_Primer_Water_Thinnable_Premium_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/calista-pro-white-primer"
  },
  {
    "name": "One Dream Duracoat",
    "family": "One",
    "slug": "one-dream-duracoat",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Dream_Duracoat.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-dream-duracoat"
  },
  {
    "name": "One Dream Effects",
    "family": "One",
    "slug": "one-dream-effects",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Dream_Marble.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-dream-effects"
  },
  {
    "name": "One Dream Effects Metallic",
    "family": "One",
    "slug": "one-dream-effects-metallic",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Dream_Texture.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-dream-effects-metallic"
  },
  {
    "name": "One Dream Marble",
    "family": "One",
    "slug": "one-dream-marble",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pro_Putty_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-dream-marble"
  },
  {
    "name": "One Dream Texture",
    "family": "One",
    "slug": "one-dream-texture",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pro_Smooth_Interior_Acrylic_Putty_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-dream-texture"
  },
  {
    "name": "One Pro Putty Primer",
    "family": "One",
    "slug": "one-pro-putty-primer",
    "category": "Interior Paints",
    "copy": "Deep-penetrating substrate primer ensuring superior adhesion and uniform sheen across interior plaster.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pro_Smooth_Interior_Primer_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pro-putty-primer"
  },
  {
    "name": "One Pro Smooth Primer",
    "family": "One",
    "slug": "one-pro-smooth-primer",
    "category": "Interior Paints",
    "copy": "Deep-penetrating substrate primer ensuring superior adhesion and uniform sheen across interior plaster.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pro_Smooth_Primer_Water_Thinnable_Luxury_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pro-smooth-primer"
  },
  {
    "name": "One Pro Smooth Putty",
    "family": "One",
    "slug": "one-pro-smooth-putty",
    "category": "Interior Paints",
    "copy": "Deep-penetrating substrate primer ensuring superior adhesion and uniform sheen across interior plaster.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pro_Smooth_Putty.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pro-smooth-putty"
  },
  {
    "name": "One Pure Elegance",
    "family": "One",
    "slug": "one-pure-elegance",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pure_Elegance.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pure-elegance"
  },
  {
    "name": "One Pure Elegance Matt",
    "family": "One",
    "slug": "one-pure-elegance-matt",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pure_Elegance_Matt.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pure-elegance-matt"
  },
  {
    "name": "One Pure Elegance Shine",
    "family": "One",
    "slug": "one-pure-elegance-shine",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pure_Elegance_Shine.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pure-elegance-shine"
  },
  {
    "name": "One Pure Elegance Soft",
    "family": "One",
    "slug": "one-pure-elegance-soft",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pure_Elegance_Soft.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pure-elegance-soft"
  },
  {
    "name": "One Pure Legend",
    "family": "One",
    "slug": "one-pure-legend",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Pure_Legend.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-pure-legend"
  },
  {
    "name": "One Timeless Clay",
    "family": "One",
    "slug": "one-timeless-clay",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Timeless_Clay.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-timeless-clay"
  },
  {
    "name": "One Timeless Marmorino",
    "family": "One",
    "slug": "one-timeless-marmorino",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Timeless_Marmorino.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-timeless-marmorino"
  },
  {
    "name": "One Timeless Marmorino Metallic",
    "family": "One",
    "slug": "one-timeless-marmorino-metallic",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Timeless_Marmorino_Metallic.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-timeless-marmorino-metallic"
  },
  {
    "name": "One Timeless Natura",
    "family": "One",
    "slug": "one-timeless-natura",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Timeless_Natura.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-timeless-natura"
  },
  {
    "name": "One Timeless Stone",
    "family": "One",
    "slug": "one-timeless-stone",
    "category": "Interior Paints",
    "copy": "Ultra-luxury interior emulsion with active stain-repellent technology and rich velvet-matte finish.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/One_Timeless_Stone.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/one-timeless-stone"
  },
  {
    "name": "Style Alpha Color Smart",
    "family": "Style",
    "slug": "style-alpha-color-smart",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Alpha_Color_Smart.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-alpha-color-smart"
  },
  {
    "name": "Style Color Fresh",
    "family": "Style",
    "slug": "style-color-fresh",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Color_Fresh.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-color-fresh"
  },
  {
    "name": "Style Color Smart",
    "family": "Style",
    "slug": "style-color-smart",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Color_Smart.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-color-smart"
  },
  {
    "name": "Style Color Smart Shine",
    "family": "Style",
    "slug": "style-color-smart-shine",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Color_Smart_Shine.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-color-smart-shine"
  },
  {
    "name": "Style Pro Fresh Primer",
    "family": "Style",
    "slug": "style-pro-fresh-primer",
    "category": "Interior Paints",
    "copy": "Deep-penetrating substrate primer ensuring superior adhesion and uniform sheen across interior plaster.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Pro_Fresh_Primer_Water_Thinnable_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-pro-fresh-primer"
  },
  {
    "name": "Style Pro Hide Primer",
    "family": "Style",
    "slug": "style-pro-hide-primer",
    "category": "Interior Paints",
    "copy": "Deep-penetrating substrate primer ensuring superior adhesion and uniform sheen across interior plaster.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Pro_Hide_Primer_Water_Thinnable_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-pro-hide-primer"
  },
  {
    "name": "Style Super Bright",
    "family": "Style",
    "slug": "style-super-bright",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Super_Bright.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-super-bright"
  },
  {
    "name": "Style Super Smooth",
    "family": "Style",
    "slug": "style-super-smooth",
    "category": "Interior Paints",
    "copy": "Rich, high-opacity interior formulation designed for bright, fresh living spaces and everyday comfort.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Super_Smooth.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-super-smooth"
  },
  {
    "name": "Style Universal Stainers",
    "family": "Style",
    "slug": "style-universal-stainers",
    "category": "Interior Paints",
    "copy": "High-strength universal stainer tinting dispersion for custom shade enrichment and depth.",
    "colour": "#D6A4A0",
    "text": "#2A1820",
    "imageUrl": "/storage/extracted/birlaopus_products_interior/Style_Universal_Stainer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/interior-wall-paint/style-universal-stainers"
  },
  {
    "name": "One Pure Elegance: Interior Paint | Birla Opus",
    "family": "One",
    "slug": "one-pure-elegance-interior-paint-birla-opus",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Pure_Elegance_Interior_Paint_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-pure-elegance-interior-paint-birla-opus"
  },
  {
    "name": "One Pro Smooth: Interior Primer | Birla Opus",
    "family": "One",
    "slug": "one-pro-smooth-interior-primer-birla-opus",
    "category": "Exterior Paints",
    "copy": "Weather-resistant exterior masonry primer sealing porosity and anchoring exterior topcoats.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Pro_Smooth_Interior_Primer_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-pro-smooth-interior-primer-birla-opus"
  },
  {
    "name": "One Pro Smooth: Interior Acrylic Putty | Birla Opus",
    "family": "One",
    "slug": "one-pro-smooth-interior-acrylic-putty-birla-opus",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Pro_Smooth_Interior_Acrylic_Putty_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-pro-smooth-interior-acrylic-putty-birla-opus"
  },
  {
    "name": "Calista Everclear: Emulsion Paint | Birla Opus",
    "family": "Calista",
    "slug": "calista-everclear-emulsion-paint-birla-opus",
    "category": "Exterior Paints",
    "copy": "High-durability exterior wall protection guarding facades against heavy monsoons, dust, and solar heat.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Calista_Everclear_Emulsion_Paint_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/calista-everclear-emulsion-paint-birla-opus"
  },
  {
    "name": "Style Colour Smart: Interior Wall Paint | Birla Opus",
    "family": "Style",
    "slug": "style-colour-smart-interior-wall-paint-birla-opus",
    "category": "Exterior Paints",
    "copy": "Weatherproof exterior acrylic formulation ensuring vibrant facade aesthetics and mold resistance.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Colour_Smart_Interior_Wall_Paint_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/style-colour-smart-interior-wall-paint-birla-opus"
  },
  {
    "name": "Style Super Bright: Exterior Acrylic Distemper | Birla Opus",
    "family": "Style",
    "slug": "style-super-bright-exterior-acrylic-distemper-birla-opus",
    "category": "Exterior Paints",
    "copy": "Weatherproof exterior acrylic formulation ensuring vibrant facade aesthetics and mold resistance.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Super_Bright_Exterior_Acrylic_Distemper_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/style-super-bright-exterior-acrylic-distemper-birla-opus"
  },
  {
    "name": "All Drywall Fix: Waterproofing Solutions | Birla Opus",
    "family": "Alldry",
    "slug": "all-drywall-fix-waterproofing-solutions-birla-opus",
    "category": "Exterior Paints",
    "copy": "Architectural exterior coating engineered to withstand extreme climates and environmental exposure.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/All_Drywall_Fix_Waterproofing_Solutions_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/all-drywall-fix-waterproofing-solutions-birla-opus"
  },
  {
    "name": "All Dry Salt Seal: Waterproofing Primer | Birla Opus",
    "family": "Alldry",
    "slug": "all-dry-salt-seal-waterproofing-primer-birla-opus",
    "category": "Exterior Paints",
    "copy": "Weather-resistant exterior masonry primer sealing porosity and anchoring exterior topcoats.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/All_Dry_Salt_Seal_Waterproofing_Primer_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/all-dry-salt-seal-waterproofing-primer-birla-opus"
  },
  {
    "name": "All Dry 2K: Waterproof Coating | Birla Opus",
    "family": "Alldry",
    "slug": "all-dry-2k-waterproof-coating-birla-opus",
    "category": "Exterior Paints",
    "copy": "Architectural exterior coating engineered to withstand extreme climates and environmental exposure.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/All_Dry_2K_Waterproof_Coating_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/all-dry-2k-waterproof-coating-birla-opus"
  },
  {
    "name": "Allwood: Interior Wood Melamine Polish | Birla Opus",
    "family": "Allwood",
    "slug": "allwood-interior-wood-melamine-polish-birla-opus",
    "category": "Exterior Paints",
    "copy": "Architectural exterior coating engineered to withstand extreme climates and environmental exposure.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Allwood_Interior_Wood_Melamine_Polish_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/allwood-interior-wood-melamine-polish-birla-opus"
  },
  {
    "name": "Allwood: Interior & Exterior Wood Paint | Birla Opus",
    "family": "Allwood",
    "slug": "allwood-interior-exterior-wood-paint-birla-opus",
    "category": "Exterior Paints",
    "copy": "Architectural exterior coating engineered to withstand extreme climates and environmental exposure.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Allwood_Interior_Exterior_Wood_Paint_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/allwood-interior-exterior-wood-paint-birla-opus"
  },
  {
    "name": "Allwood: Italian PU Paint | Birla Opus",
    "family": "Allwood",
    "slug": "allwood-italian-pu-paint-birla-opus",
    "category": "Exterior Paints",
    "copy": "Architectural exterior coating engineered to withstand extreme climates and environmental exposure.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Allwood_Italian_PU_Paint_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/allwood-italian-pu-paint-birla-opus"
  },
  {
    "name": "Alpha Power Bright",
    "family": "Alpha",
    "slug": "alpha-power-bright",
    "category": "Exterior Paints",
    "copy": "Weatherproof exterior acrylic formulation ensuring vibrant facade aesthetics and mold resistance.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Alpha_Power_Bright.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/alpha-power-bright"
  },
  {
    "name": "Calista Neo Floor Shade",
    "family": "Calista",
    "slug": "calista-neo-floor-shade",
    "category": "Exterior Paints",
    "copy": "High-durability exterior wall protection guarding facades against heavy monsoons, dust, and solar heat.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Calista_Neo_Floor_Shade.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/calista-neo-floor-shade"
  },
  {
    "name": "Calista Neo Star",
    "family": "Calista",
    "slug": "calista-neo-star",
    "category": "Exterior Paints",
    "copy": "High-durability exterior wall protection guarding facades against heavy monsoons, dust, and solar heat.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Calista_Neo_Star.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/calista-neo-star"
  },
  {
    "name": "Calista Neo Star Shine",
    "family": "Calista",
    "slug": "calista-neo-star-shine",
    "category": "Exterior Paints",
    "copy": "High-durability exterior wall protection guarding facades against heavy monsoons, dust, and solar heat.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Calista_Neo_Star_Shine.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/calista-neo-star-shine"
  },
  {
    "name": "Calista Neo Tile Shade",
    "family": "Calista",
    "slug": "calista-neo-tile-shade",
    "category": "Exterior Paints",
    "copy": "High-durability exterior wall protection guarding facades against heavy monsoons, dust, and solar heat.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Calista_Neo_Tile_Shade.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/calista-neo-tile-shade"
  },
  {
    "name": "Calista Perfect Choice Primer",
    "family": "Calista",
    "slug": "calista-perfect-choice-primer",
    "category": "Exterior Paints",
    "copy": "Weather-resistant exterior masonry primer sealing porosity and anchoring exterior topcoats.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Calista_Perfect_Choice_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/calista-perfect-choice-primer"
  },
  {
    "name": "One Explore 15",
    "family": "One",
    "slug": "one-explore-15",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Explore_15.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-explore-15"
  },
  {
    "name": "One Explore Roller",
    "family": "One",
    "slug": "one-explore-roller",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Explore_Roller.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-explore-roller"
  },
  {
    "name": "One Inspire Clear Coat",
    "family": "One",
    "slug": "one-inspire-clear-coat",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Inspire_Clear_Coat.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-inspire-clear-coat"
  },
  {
    "name": "One Inspire Concrete",
    "family": "One",
    "slug": "one-inspire-concrete",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_Inspire_Concrete.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-inspire-concrete"
  },
  {
    "name": "One True Flex",
    "family": "One",
    "slug": "one-true-flex",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_True_Flex.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-true-flex"
  },
  {
    "name": "One True Life",
    "family": "One",
    "slug": "one-true-life",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_True_Life.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-true-life"
  },
  {
    "name": "One True Look",
    "family": "One",
    "slug": "one-true-look",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_True_Look.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-true-look"
  },
  {
    "name": "One True Vision",
    "family": "One",
    "slug": "one-true-vision",
    "category": "Exterior Paints",
    "copy": "All-weather elastomeric exterior shield with crack-bridging elasticity, anti-algal shield, and UV reflection.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/One_True_Vision.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/one-true-vision"
  },
  {
    "name": "Style Perfect Start Primer",
    "family": "Style",
    "slug": "style-perfect-start-primer",
    "category": "Exterior Paints",
    "copy": "Weather-resistant exterior masonry primer sealing porosity and anchoring exterior topcoats.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Perfect_Start_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/style-perfect-start-primer"
  },
  {
    "name": "Style Power Bright",
    "family": "Style",
    "slug": "style-power-bright",
    "category": "Exterior Paints",
    "copy": "Weatherproof exterior acrylic formulation ensuring vibrant facade aesthetics and mold resistance.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Power_Bright.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/style-power-bright"
  },
  {
    "name": "Style Power Bright Shine",
    "family": "Style",
    "slug": "style-power-bright-shine",
    "category": "Exterior Paints",
    "copy": "Weatherproof exterior acrylic formulation ensuring vibrant facade aesthetics and mold resistance.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Power_Bright_Shine.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/style-power-bright-shine"
  },
  {
    "name": "Style Power Fit",
    "family": "Style",
    "slug": "style-power-fit",
    "category": "Exterior Paints",
    "copy": "Weatherproof exterior acrylic formulation ensuring vibrant facade aesthetics and mold resistance.",
    "colour": "#33584B",
    "text": "#F8F5E9",
    "imageUrl": "/storage/extracted/birlaopus_products_exterior/Style_Power_Fit.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/exterior-wall-paint/style-power-fit"
  },
  {
    "name": "Alldry Crack Master Paste",
    "family": "Alldry",
    "slug": "alldry-crack-master-paste",
    "category": "Waterproofing",
    "copy": "High-strength polymer crack filler and joint sealant preventing moisture ingress through masonry.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Crack_Master_Paste.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-crack-master-paste"
  },
  {
    "name": "Alldry Repair Master",
    "family": "Alldry",
    "slug": "alldry-repair-master",
    "category": "Waterproofing",
    "copy": "Hydrophobic polymer barrier engineered for deep substrate sealing and long-term moisture defense.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Repair_Master.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-repair-master"
  },
  {
    "name": "Alldry Salt Seal",
    "family": "Alldry",
    "slug": "alldry-salt-seal",
    "category": "Waterproofing",
    "copy": "Hydrophobic polymer barrier engineered for deep substrate sealing and long-term moisture defense.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Salt_Seal.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-salt-seal"
  },
  {
    "name": "Alldry Total 2K Flex",
    "family": "Alldry",
    "slug": "alldry-total-2k-flex",
    "category": "Waterproofing",
    "copy": "Hydrophobic polymer barrier engineered for deep substrate sealing and long-term moisture defense.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Total_2K_Flex.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-total-2k-flex"
  },
  {
    "name": "Alldry Total 2K",
    "family": "Alldry",
    "slug": "alldry-total-2k",
    "category": "Waterproofing",
    "copy": "Hydrophobic polymer barrier engineered for deep substrate sealing and long-term moisture defense.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Total_2K.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-total-2k"
  },
  {
    "name": "Alldry Total Stop",
    "family": "Alldry",
    "slug": "alldry-total-stop",
    "category": "Waterproofing",
    "copy": "Hydrophobic polymer barrier engineered for deep substrate sealing and long-term moisture defense.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Wall_Fix_4.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-total-stop"
  },
  {
    "name": "Alldry Total Win",
    "family": "Alldry",
    "slug": "alldry-total-win",
    "category": "Waterproofing",
    "copy": "Hydrophobic polymer barrier engineered for deep substrate sealing and long-term moisture defense.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Wall_n_Roof_10.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-total-win"
  },
  {
    "name": "Alldry Wall Fix 4",
    "family": "Alldry",
    "slug": "alldry-wall-fix-4",
    "category": "Waterproofing",
    "copy": "High-strength polymer crack filler and joint sealant preventing moisture ingress through masonry.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Alldry_Wall_n_Roof_12.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-wall-fix-4"
  },
  {
    "name": "Alldry Wall N Roof 10",
    "family": "Alldry",
    "slug": "alldry-wall-n-roof-10",
    "category": "Waterproofing",
    "copy": "Advanced elastomeric waterproofing membrane providing seamless protection for roofs and terraces.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/All_Drywall_Fix_Waterproofing_Solutions_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-wall-n-roof-10"
  },
  {
    "name": "Alldry Wall N Roof 12",
    "family": "Alldry",
    "slug": "alldry-wall-n-roof-12",
    "category": "Waterproofing",
    "copy": "Advanced elastomeric waterproofing membrane providing seamless protection for roofs and terraces.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/All_Dry_2K_Waterproof_Coating_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-wall-n-roof-12"
  },
  {
    "name": "Alldry Wall N Roof 14",
    "family": "Alldry",
    "slug": "alldry-wall-n-roof-14",
    "category": "Waterproofing",
    "copy": "Advanced elastomeric waterproofing membrane providing seamless protection for roofs and terraces.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/All_Dry_Salt_Seal_Waterproofing_Primer_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-wall-n-roof-14"
  },
  {
    "name": "Alldry Wall N Roof 7",
    "family": "Alldry",
    "slug": "alldry-wall-n-roof-7",
    "category": "Waterproofing",
    "copy": "Advanced elastomeric waterproofing membrane providing seamless protection for roofs and terraces.",
    "colour": "#759FBA",
    "text": "#152633",
    "imageUrl": "/storage/extracted/birlaopus_products_waterproofing/Home_Paint_Interior_Wall_Paint_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/waterproofing/alldry-wall-n-roof-7"
  },
  {
    "name": "Calista Sparkle Gloss",
    "family": "Calista",
    "slug": "calista-sparkle-gloss",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Calista_Sparkle_Gloss.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-sparkle-gloss"
  },
  {
    "name": "Calista Sparkle PU",
    "family": "Calista",
    "slug": "calista-sparkle-pu",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Calista_Sparkle_Gloss_Enamel_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-sparkle-pu"
  },
  {
    "name": "Calista Sparkle Red Oxide Primer",
    "family": "Calista",
    "slug": "calista-sparkle-red-oxide-primer",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Calista_Sparkle_Red_Oxide_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-sparkle-red-oxide-primer"
  },
  {
    "name": "Calista Sparkle Satin",
    "family": "Calista",
    "slug": "calista-sparkle-satin",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Calista_Sparkle_Satin.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-sparkle-satin"
  },
  {
    "name": "Calista Sparkle Wood Primer White",
    "family": "Calista",
    "slug": "calista-sparkle-wood-primer-white",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Calista_Pro_White_Cement_ST_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-sparkle-wood-primer-white"
  },
  {
    "name": "Calista Sparkle Yellow Metal Primer",
    "family": "Calista",
    "slug": "calista-sparkle-yellow-metal-primer",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Calista_Sparkle_Yellow_Metal_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-sparkle-yellow-metal-primer"
  },
  {
    "name": "Calista Pro White Cement ST Primer",
    "family": "Calista",
    "slug": "calista-pro-white-cement-st-primer",
    "category": "Enamels",
    "copy": "High-durability solvent-thinnable enamel crafted for architectural trims, gates, grills, and woodwork.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Style_Pro_Hide_Cement_ST_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/calista-pro-white-cement-st-primer"
  },
  {
    "name": "Style Cover Max Gloss",
    "family": "Style",
    "slug": "style-cover-max-gloss",
    "category": "Enamels",
    "copy": "Mirror-gloss polyurethane enamel delivering rich luster and corrosion resistance for wood and metal.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Style_Cover_Max_Gloss.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/style-cover-max-gloss"
  },
  {
    "name": "Style Cover Max Red Oxide Primer",
    "family": "Style",
    "slug": "style-cover-max-red-oxide-primer",
    "category": "Enamels",
    "copy": "High-durability solvent-thinnable enamel crafted for architectural trims, gates, grills, and woodwork.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/Style_Cover_Max_Red_Oxide_Primer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/style-cover-max-red-oxide-primer"
  },
  {
    "name": "Style Pro Hide Cement ST Primer",
    "family": "Style",
    "slug": "style-pro-hide-cement-st-primer",
    "category": "Enamels",
    "copy": "High-durability solvent-thinnable enamel crafted for architectural trims, gates, grills, and woodwork.",
    "colour": "#E3C646",
    "text": "#2A2310",
    "imageUrl": "/storage/extracted/birlaopus_products_enamels/One_Pro_Smooth_Interior_Primer_Birla_Opus_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/enamels-paints/style-pro-hide-cement-st-primer"
  },
  {
    "name": "Allwood Italian PU",
    "family": "Allwood",
    "slug": "allwood-italian-pu",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_Italian_PU.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-italian-pu"
  },
  {
    "name": "Allwood Melamine",
    "family": "Allwood",
    "slug": "allwood-melamine",
    "category": "Wood Finishes",
    "copy": "Silky-touch protective wood finish preserving interior timber texture and resisting heat stains.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_Interior_Wood_Melamine_Polish_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-melamine"
  },
  {
    "name": "Allwood Melamine Ultra Clear",
    "family": "Allwood",
    "slug": "allwood-melamine-ultra-clear",
    "category": "Wood Finishes",
    "copy": "Silky-touch protective wood finish preserving interior timber texture and resisting heat stains.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_Melamine_Ultra_Clear.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-melamine-ultra-clear"
  },
  {
    "name": "Allwood NC Sanding Sealer",
    "family": "Allwood",
    "slug": "allwood-nc-sanding-sealer",
    "category": "Wood Finishes",
    "copy": "Specialist timber finish protecting architectural woodwork and furniture with rich depth of grain.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_NC_Sanding_Sealer.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-nc-sanding-sealer"
  },
  {
    "name": "Allwood PU Color Exterior",
    "family": "Allwood",
    "slug": "allwood-pu-color-exterior",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_PU_Color_Exterior.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-pu-color-exterior"
  },
  {
    "name": "Allwood PU Color Interior",
    "family": "Allwood",
    "slug": "allwood-pu-color-interior",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_PU_Color_Interior.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-pu-color-interior"
  },
  {
    "name": "Allwood PU Color Metallic",
    "family": "Allwood",
    "slug": "allwood-pu-color-metallic",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_PU_Color_Metallic.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-pu-color-metallic"
  },
  {
    "name": "Allwood PU Exterior",
    "family": "Allwood",
    "slug": "allwood-pu-exterior",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_Interior_Exterior_Wood_Paint_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-pu-exterior"
  },
  {
    "name": "Allwood PU Interior",
    "family": "Allwood",
    "slug": "allwood-pu-interior",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_PU_Interior.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-pu-interior"
  },
  {
    "name": "Allwood PU Thinner",
    "family": "Allwood",
    "slug": "allwood-pu-thinner",
    "category": "Wood Finishes",
    "copy": "Italian-grade polyurethane coating delivering crystal clarity, grain enhancement, and scratch resistance.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_PU_Thinner.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-pu-thinner"
  },
  {
    "name": "Allwood SFX",
    "family": "Allwood",
    "slug": "allwood-sfx",
    "category": "Wood Finishes",
    "copy": "Specialist timber finish protecting architectural woodwork and furniture with rich depth of grain.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_SFX_Special_Effects_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-sfx"
  },
  {
    "name": "Allwood SoftTouch",
    "family": "Allwood",
    "slug": "allwood-softtouch",
    "category": "Wood Finishes",
    "copy": "Silky-touch protective wood finish preserving interior timber texture and resisting heat stains.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_SoftTouch_1K_PU.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-softtouch"
  },
  {
    "name": "Allwood Wood Filler",
    "family": "Allwood",
    "slug": "allwood-wood-filler",
    "category": "Wood Finishes",
    "copy": "Specialist timber finish protecting architectural woodwork and furniture with rich depth of grain.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_Wood_Filler.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-wood-filler"
  },
  {
    "name": "Allwood Wood Stain",
    "family": "Allwood",
    "slug": "allwood-wood-stain",
    "category": "Wood Finishes",
    "copy": "Specialist timber finish protecting architectural woodwork and furniture with rich depth of grain.",
    "colour": "#AD7048",
    "text": "#2B1C13",
    "imageUrl": "/storage/extracted/birlaopus_products_woodfinishes/Allwood_Wood_Stain.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wood-paint/allwood-wood-stain"
  },
  {
    "name": "Tropical Flair Wallpaper: Interior Texture | Birla Opus",
    "family": "Tropical Flair",
    "slug": "tropical-flair-wallpaper-interior-texture-birla-opus",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Tropical_Flair_Wallpaper_Interior_Texture_Birla_Opus.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/tropical-flair-wallpaper-interior-texture-birla-opus"
  },
  {
    "name": "Birla Opus | Animal, Bird & Insect",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-animal-bird-insect",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Animal_Bird_Insect.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-animal-bird-insect"
  },
  {
    "name": "Birla Opus | Heritage collection",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-heritage-collection",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Heritage_collection.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-heritage-collection"
  },
  {
    "name": "Birla Opus | Florals",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-florals",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Florals.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-florals"
  },
  {
    "name": "Birla Opus | Food",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-food",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Food.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-food"
  },
  {
    "name": "Birla Opus | Ethnic",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-ethnic",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Ethnic.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-ethnic"
  },
  {
    "name": "Birla Opus | Bricks & Stones",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-bricks-stones",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Bricks_Stones.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-bricks-stones"
  },
  {
    "name": "Birla Opus | Woods",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-woods",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Woods.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-woods"
  },
  {
    "name": "Birla Opus | Natural Imitations",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-natural-imitations",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Natural_Imitations.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-natural-imitations"
  },
  {
    "name": "Birla Opus | Damask",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-damask",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Damask.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-damask"
  },
  {
    "name": "Birla Opus | Signature collection",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-signature-collection",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Signature_collection.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-signature-collection"
  },
  {
    "name": "Birla Opus | Geometric Retreat",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-geometric-retreat",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Geometric_Retreat.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-geometric-retreat"
  },
  {
    "name": "Birla Opus | Timeless Damask",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-timeless-damask",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Timeless_Damask.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-timeless-damask"
  },
  {
    "name": "Birla Opus | Garden Charms",
    "family": "Wallpaper Collection",
    "slug": "birla-opus-garden-charms",
    "category": "Wallpapers",
    "copy": "Bespoke designer wallcovering featuring intricate relief textures and tactile artisan patterns.",
    "colour": "#D7A7B5",
    "text": "#2B1D26",
    "imageUrl": "/storage/extracted/birlaopus_wallpaper/Birla_Opus_Garden_Charms.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/wallpapers/birla-opus-garden-charms"
  },
  {
    "name": "Birla Opus Artist DF Cloud Roller",
    "family": "Artist",
    "slug": "birla-opus-artist-df-cloud-roller",
    "category": "Tools",
    "copy": "Precision microfibre paint roller designed for smooth, streak-free emulsion and texture application.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Birla_Opus_Artist_DF_Cloud_Roller.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/birla-opus-artist-df-cloud-roller"
  },
  {
    "name": "Artist Waterproof Sandpaper",
    "family": "Artist",
    "slug": "artist-waterproof-sandpaper",
    "category": "Tools",
    "copy": "Master-grade application tool engineered for professional precision and effortless handling.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Artist_Waterproof_Sandpaper.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/artist-waterproof-sandpaper"
  },
  {
    "name": "Artist Painter's Masking Tape 2\"",
    "family": "Artist",
    "slug": "artist-painters-masking-tape-2",
    "category": "Tools",
    "copy": "Professional painter masking tape providing razor-sharp edge lines with residue-free removal.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Artist_Painter_s_Masking_Tape_1_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/artist-painters-masking-tape-2"
  },
  {
    "name": "Artist Painter's Masking Tape 1.5\"",
    "family": "Artist",
    "slug": "artist-painters-masking-tape-1-5",
    "category": "Tools",
    "copy": "Professional painter masking tape providing razor-sharp edge lines with residue-free removal.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Artist_Painter_s_Masking_Tape_1_5_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/artist-painters-masking-tape-1-5"
  },
  {
    "name": "Artist Painter's Masking Tape 1\"",
    "family": "Artist",
    "slug": "artist-painters-masking-tape-1",
    "category": "Tools",
    "copy": "Professional painter masking tape providing razor-sharp edge lines with residue-free removal.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Artist_Painter_s_Masking_Tape_2_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/artist-painters-masking-tape-1"
  },
  {
    "name": "Birla Opus Artist Exterior Felt Roller 9\"",
    "family": "Artist",
    "slug": "birla-opus-artist-exterior-felt-roller-9",
    "category": "Tools",
    "copy": "Precision microfibre paint roller designed for smooth, streak-free emulsion and texture application.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Birla_Opus_Artist_Exterior_Felt_Roller_9_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/birla-opus-artist-exterior-felt-roller-9"
  },
  {
    "name": "Birla Opus Artist Interior Felt Roller 9\"",
    "family": "Artist",
    "slug": "birla-opus-artist-interior-felt-roller-9",
    "category": "Tools",
    "copy": "Precision microfibre paint roller designed for smooth, streak-free emulsion and texture application.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Birla_Opus_Artist_Interior_Felt_Roller_6_4_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/birla-opus-artist-interior-felt-roller-9"
  },
  {
    "name": "Birla Opus Artist Interior Felt Roller 6 &4\"",
    "family": "Artist",
    "slug": "birla-opus-artist-interior-felt-roller-6-4",
    "category": "Tools",
    "copy": "Precision microfibre paint roller designed for smooth, streak-free emulsion and texture application.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Birla_Opus_Artist_Interior_Felt_Roller_9_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/birla-opus-artist-interior-felt-roller-6-4"
  },
  {
    "name": "Birla Opus Artist Interior Foam Roller 6 & 4\"",
    "family": "Artist",
    "slug": "birla-opus-artist-interior-foam-roller-6-4",
    "category": "Tools",
    "copy": "Precision microfibre paint roller designed for smooth, streak-free emulsion and texture application.",
    "colour": "#8FA7C8",
    "text": "#172333",
    "imageUrl": "/storage/extracted/birlaopus_products_tools/Birla_Opus_Artist_Interior_Foam_Roller_6_4_.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/tools/birla-opus-artist-interior-foam-roller-6-4"
  },
  {
    "name": "Birla Opus One Aero Spray Paint",
    "family": "One Aero",
    "slug": "birla-opus-one-aero-spray-paint",
    "category": "Aerosols",
    "copy": "Fast-drying, high-atomization acrylic spray paint for seamless touch-ups, metallic crafts, and trims.",
    "colour": "#D5CD55",
    "text": "#262600",
    "imageUrl": "/storage/extracted/birlaopus_products_aerosols/Birla_Opus_One_Aero_Spray_Paint.webp",
    "sourceUrl": "https://www.birlaopus.com/paint-products/aerosols/birla-opus-one-aero-spray-paint"
  }
] as const;
