export const businessProfile = {
  name: "JAYMURTI TRADERS",
  hindiName: "जयमूर्ति ट्रेडर्स",
  businessType: "Birla Opus Paint Dealer / Paint & Colour Showroom",
  brand: "Birla Opus",
  address: "Shukul Bazar, Baskhari, Ambedkar Nagar, Uttar Pradesh - 224129, India",
  landmark: "Shukul Bazar, Baskhari",
  pincode: "224129",
  phoneDisplay: "+91 87566 59035",
  phoneHref: "+918756659035",
  whatsappHref: "918756659035",
  hours: "8:00 AM – 9:00 PM",
  instagramHandle: "@paintwalebhaiya45",
  instagramUrl: "https://www.instagram.com/paintwalebhaiya45",
  facebookUrl: "https://www.facebook.com/ayush.yadav.334540",
  googleProfileUrl: "https://share.google/Nyju9PoRuINGGoD83",
  googleReviewUrl: "https://share.google/Nyju9PoRuINGGoD83",
  googleMapsUrl: "https://maps.app.goo.gl/JZJa7km7nj6fACoA6",
  verifiedOfferings: [
    "Birla Opus interior emulsions",
    "Birla Opus exterior paints",
    "Colour tinting & shade consultation",
    "Waterproofing solutions",
    "Enamels & wood finishes",
    "Painting tools & supplies",
  ],
} as const;
