export const businessProfile = {
  name: "Jaymurti Traders",
  nameHindi: "जयमूर्ति ट्रेडर्स",
  brand: "Birla Opus",
  address: "Shukul Bazar, Baskhari, Ambedkar Nagar, Uttar Pradesh - 224129, India",
  landmark: "Shukul Bazar, Baskhari",
  pincode: "224129",
  phoneDisplay: "+91 8756659035",
  phoneHref: "+918756659035",
  whatsappHref: "918756659035",
  email: "",
  hours: "8:00 AM – 9:00 PM",
  instagramHandle: "@paintwalebhaiya45",
  instagramUrl: "https://www.instagram.com/paintwalebhaiya45?utm_source=ig_web_button_share_sheet&stkn=ZDNlZDc0MzIxNw==",
  googleProfileUrl: "https://share.google/Nyju9PoRuINGGoD83",
  googleReviewUrl: "https://share.google/Nyju9PoRuINGGoD83",
  googleMapsUrl: "https://maps.app.goo.gl/V1wvtKAGnH5RUG1cA",
  owner: "",
  verifiedOfferings: [
    "Birla Opus interior emulsions",
    "Easy-to-clean, low-odour formulations",
    "Colour Fresh",
    "Pure Elegance Shyne",
    "Calista Sparkle Gloss Enamel",
    "Birla Opus Metal finishes",
  ],
} as const;
